apiVersion: v1
kind: Secret
metadata:
  name: overview-broker-secret
type: Opaque
data:
  {{- if .Values.brokerUsername }}
  username: {{ .Values.brokerUsername | b64enc | quote }}
  {{- else }}
  username: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
  {{- if .Values.brokerPassword }}
  password: {{ .Values.brokerPassword | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overview-broker.fullname" . }}
  labels:
    {{- include "overview-broker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "overview-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "overview-broker.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "overview-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
          - name: BROKER_USERNAME
            valueFrom:
              secretKeyRef:
                name: overview-broker-secret
                key: username
          - name: BROKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: overview-broker-secret
                key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
